### ISSUE TITLE
User Profiles

### ISSUE THREAD

**Issue by danaalyse** [Team-Goatr/Makerspace-Automation-Suite#19] opened 2017-01-12 01:16 UTC
Generate user profiles from user registrations.

**Comment by ryanstrat** [comment] 2017-02-19 22:30
This seems like a duplicate of #17

**Comment by ryanstrat** [comment] 2017-02-22 16:31
Just need to fix the date field to actually store in G Suite

**Comment by ryanstrat** [comment] 2017-03-15 15:15
This was completed.

**Closed as completed by ryanstrat** 2017-03-15 15:15 UTC
Labels: Epic, Backend
